/**
 * Levels
 *
 * The level data in this file is generated by the level files in `src/levels` during the gulp build.
 * If you like, you can add additional level files there by creating them in your text editor,
 * then add the name of your new level in the level order list below.
 */

// Generated by `gulp generateLevelData`
export const Levels =
/* <generated> */
[ { name: 'Easy Street',
    time: 35,
    rocks: 5,
    layout:
     [ '                                       V                 $',
       '                                                         H',
       '                H                                        H',
       '       =========H==================================================',
       '                H',
       '                H',
       '                H          H                             H',
       '================H==========H==================   ========H=====================',
       '                &          H                             H          |       |',
       '                                                         H         Easy Street',
       '                H                                        H',
       '       =========H==========H=========  =======================',
       '                H',
       '                H',
       '                H                                        H',
       '======================== ====================== =========H==============',
       '                                                         H',
       '                                                         H',
       '*    p                                                   H                    *',
       '===============================================================================',
       '' ] },
  { name: 'Long Island',
    time: 45,
    rocks: 8,
    layout:
     [ '                                                                          $',
       '                                                                   &      H',
       '    H       |V                                                     V|     H',
       '====H======================= ========================= ======================',
       '    H',
       '    H',
       '    H                    & |                         . .                  H',
       '========================== ======  =================== ===================H==',
       '                                                                          H',
       '                                  |                                       H',
       '    H                             |                 .  .                  H',
       '====H=====================   ======  ================  ======================',
       '    H',
       '    H                      |',
       '    H                      |                        .   .                 H',
       '=========================  ========    ==============   ==================H==',
       '                                                                          H',
       '==============                      |                                     H',
       ' Long Island |   p         *        |                 *                   H',
       '===============================================================================',
       '' ] } ]
/* </generated> */
;
